spring.datasource.url=jdbc:postgresql://localhost:5433/meu_banco
spring.datasource.username=postgres
spring.datasource.password=minhasenha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

resend.api.key=re_csNtD42F_E3xjSewMu2E9ViUYCwKMtqsg